//User constants
export const SEND_CREATE_USER = "SEND_CREATE_USER";
export const RECEIVE_CREATE_USER = "RECEIVE_CREATE_USER";

export const SEND_UPDATE_USER = "SEND_UPDATE_USER";
export const RECEIVE_UPDATE_USER = "RECEIVE_UPDATE_USER";

export const SEND_USER_AUTHENTICATE = "SEND_USER_AUTHENTICATE";
export const RECEIVE_USER_AUTHENTICATE = "RECEIVE_USER_AUTHENTICATE";

export const SEND_USER_PROFILE = "SEND_USER_PROFILE";
export const RECEIVE_USER_PROFILE = "RECEIVE_USER_PROFILE";

export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const CALL_ERROR = "CALL_ERROR";

export const LOG_OUT_USER = "LOG_OUT_USER";

//Location Constants
export const ADD_LOCATION = "ADD_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const REQUEST_LOCATIONS = "REQUEST_LOCATIONS";
export const RECEIVE_LOCATIONS = "RECEIVE_LOCATIONS";

export const VALIDATE_APPOINTMENT = "VALIDATE_APPOINTMENT";
export const VALID_APPOINTMENT = "VALID_APPOINTMENT";
export const INVALID_APPOINTMENT = "INVALID_APPOINTMENT";
export const SENDING_APPOINTMENT = "SENDING_APPOINTMENT";
export const SENT_APPOINTMENT = "SENT_APPOINTMENT";

//Practice Constants
export const SEND_CREATE_PRACTICE = "SEND_CREATE_PRACTICE";
export const RECEIVE_CREATE_PRACTICE = "RECEIVE_CREATE_PRACTICE";

export const SEND_PRACTICE_EDIT = "SEND_PRACTICE_EDIT";
export const RECEIVE_PRACTICE_EDIT = "RECEIVE_PRACTICE_EDIT";

export const SEND_GET_PRACTICE = "SEND_GET_PRACTICE";
export const RECEIVE_GET_PRACTICE = "RECEIVE_GET_PRACTICE";

export const UPDATE_PRACTICE = "UPSDATE_PRACTICE";
export const GET_PRACTICE_LOCATIONS = "GET_PRACTICE_LOCATIONS";
