//User constants
export const SET_USER = "SET_USER";
export const SEND_CREATE_USER = "SEND_CREATE_USER";
export const RECIEVE_CREATE_USER = "RECIEVE_CREATE_USER";
export const SEND_USER_AUTHENTICATE = "SEND_USER_AUTHENTICATE";
export const RECIEVE_USER_AUTHENTICATE = "RECIEVE_USER_AUTHENTICATE";
export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

//Location Constants
export const ADD_LOCATION = "ADD_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const REQUEST_LOCATIONS = "REQUEST_LOCATIONS";
export const RECIEVE_LOCATIONS = "RECIEVE_LOCATIONS";

//Practice Constants
export const CREATE_PRACTICE = "CREATE_PRACTICE";
export const UPDATE_PRACTICE = "UPSDATE_PRACTICE";
export const GET_PRACTICE_LOCATIONS = "GET_PRACTICE_LOCATIONS";
