//User constants
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const CREATE_USER = "CREATE_USER";
export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";

//Location Constants
export const ADD_LOCATION = "ADD_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const REQUEST_LOCATIONS = "REQUEST_LOCATIONS";
export const RECIEVE_LOCATIONS = "RECIEVE_LOCATIONS";

//Practice Constants
export const CREATE_PRACTICE = "CREATE_PRACTICE";
export const UPDATE_PRACTICE = "UPSDATE_PRACTICE";
export const GET_PRACTICE_LOCATIONS = "GET_PRACTICE_LOCATIONS";
